version: 0.1

phases:
  install:
    commands:
      - echo install started on `date`
      - gem install bundler
      - bundle install
  build:
    commands:
      - echo Build started on `date`
      - bundle exec rails test
  post_build:
    commands:
      - echo Build completed on `date`